### ISSUE TITLE
unable to locate module include.settings

### ISSUE THREAD

**Issue by Vikash84** [us-spd/SPAR#1]
File "run.py", line 15, in <module>
    from include.sequence_annotate import sequence_annotate
  File "/home/vsingh/softwares/SPAR/include/sequence_annotate.py", line 19, in <module>
    from .settings import bash_path, translational_frameshift_di
ModuleNotFoundError: No module named 'include.settings'

**Comment by tkanderson** [comment]
Thanks @Vikash84 Blake is working on an update and will push shortly. This should resolve the issue. We appreciate you checking out the tool, and welcome any additional comments/feedback.

**Comment by btski** [comment]
I have amended the repo to include the most recent version of SPAR. This should resolve the pathing issue you encountered @Vikash84. Please let me know if you experience any other problems.

**Comment by Vikash84** [comment]
Thanks, it is working now.
